[package]
name = "ds41rt-loader"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
libc.workspace = true
ds41rt-core = { path = "../ds41rt-core" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokenizers.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
