#!/usr/bin/env python3
"""Real four-Spark routed expert planes and RTX shared reduction versus official FP4 experts."""
import argparse,ast,hashlib,importlib.util,json,struct
from pathlib import Path
from types import SimpleNamespace
import torch
import tvm_ffi


def main():
    p=argparse.ArgumentParser(description=__doc__)
    for name in ('reference-dir','snapshot','vectors-dir','rank-dir','output'):p.add_argument('--'+name,type=Path,required=True)
    p.add_argument('--device',type=int,required=True);p.add_argument('--layer',type=int,default=0);a=p.parse_args()
    root=Path(__file__).resolve().parents[1];lock=json.loads((root/'docs/ds41-reference-lock.json').read_text())
    for name in ('model.py','kernel.py'):
        assert hashlib.sha256((a.reference_dir/'inference'/name).read_bytes()).hexdigest()==lock['files']['inference/'+name]
    source=a.reference_dir/'inference/model.py';expert=next(n for n in ast.parse(source.read_text()).body if isinstance(n,ast.ClassDef) and n.name=='Expert')
    forward=next(n for n in expert.body if isinstance(n,ast.FunctionDef) and n.name=='forward')
    ns={'torch':torch,'F':torch.nn.functional};exec(compile(ast.Module(body=[forward],type_ignores=[]),str(source),'exec'),ns)
    spec=importlib.util.spec_from_file_location('ds41_official_kernel',a.reference_dir/'inference/kernel.py')
    ref=importlib.util.module_from_spec(spec);spec.loader.exec_module(ref);assert ref.tilelang.__version__=='0.1.8'
    ref.act_quant_kernel.pass_configs={**ref.act_quant_kernel.pass_configs,'tir.disable_vectorize':True}
    torch.cuda.set_device(a.device);torch.set_default_dtype(torch.bfloat16)
    stream=torch.cuda.Stream();index=json.loads((a.snapshot/'model.safetensors.index.json').read_text())['weight_map'];headers={};hashes={};payloads={};results=[]
    def load(path,dtype,shape):
        raw=path.read_bytes();payloads[str(path)]=hashlib.sha256(raw).hexdigest()
        return torch.frombuffer(bytearray(raw),dtype=dtype).reshape(shape).cuda()
    def weight(name,dtype):
        path=a.snapshot/index[name]
        with path.open('rb') as f:
            if path not in headers:
                n=struct.unpack('<Q',f.read(8))[0];headers[path]=(n,json.loads(f.read(n)))
            n,h=headers[path];e=h[name];begin,end=e['data_offsets'];f.seek(8+n+begin);raw=f.read(end-begin)
        hashes[name]=hashlib.sha256(raw).hexdigest();return torch.frombuffer(bytearray(raw),dtype=dtype).reshape(e['shape']).cuda()
    def linear(x,w):
        q,s=ref.act_quant(x.contiguous(),32,'ue8m0',torch.float8_e8m0fnu)
        return ref.fp4_gemm(q,s,*w,torch.float8_e8m0fnu,act_block_size=32)
    def compare(actual,expected):
        x,y=actual.float(),expected.float();assert torch.isfinite(x).all() and torch.isfinite(y).all()
        rel=((x-y).norm()/y.norm()).item();cos=torch.nn.functional.cosine_similarity(x.flatten(),y.flatten(),dim=0).item()
        assert rel<.01 and cos>.9999,(rel,cos)
        return dict(relative_l2=rel,cosine=cos,max_abs=(x-y).abs().max().item())
    with torch.device('cuda'),torch.cuda.stream(stream),tvm_ffi.use_torch_stream(),torch.no_grad():
        cases=[]
        for case in (0,1):
            prefix=a.vectors_dir/'router'/f'l{a.layer}-m80-c{case}'
            hidden=load(Path(str(prefix)+'-input.bin'),torch.bfloat16,(80,5120))
            ids=load(Path(str(prefix)+'-ids.bin'),torch.int32,(80,6));routing=load(Path(str(prefix)+'-routing.bin'),torch.float32,(80,6))
            shared=load(a.vectors_dir/'shared'/f'l{a.layer}-m80-c0-output.bin',torch.bfloat16,(80,5120))
            output=load(a.vectors_dir/f'l{a.layer}/ffn-transport-c{case}.bin',torch.bfloat16,(80,5120))
            planes=[load(a.rank_dir/f'rank{rank}/l{a.layer}-c{case}-plane.bin',torch.float32,(80,6,5120)) for rank in range(4)]
            # The worker records the actual received frame. Check all four against
            # the immutable request generated by the bound router output.
            frame=Path(str(prefix)+'-request.bin').read_bytes()
            for rank in range(4):assert (a.rank_dir/f'rank{rank}/l{a.layer}-c{case}-request.bin').read_bytes()==frame
            summed=planes[0].clone()
            for plane in planes[1:]:summed+=plane
            routed=summed.bfloat16();total=torch.zeros((80,5120),dtype=torch.float32)
            for slot in range(6):total+=routed[:,slot].float()
            total+=shared.float();torch.testing.assert_close(output,total.bfloat16(),rtol=0,atol=0)
            cases.append(dict(case=case,hidden=hidden,ids=ids,routing=routing,shared=shared,output=output,routed=routed,expected=torch.empty_like(routed),experts=[]))
        active=sorted(set(cases[0]['ids'].flatten().tolist()+cases[1]['ids'].flatten().tolist()))
        for expert_id in active:
            prefix=f'layers.{a.layer}.ffn.experts.{expert_id}'
            weights={name:(weight(f'{prefix}.{name}.weight',torch.float4_e2m1fn_x2),weight(f'{prefix}.{name}.scale',torch.float8_e8m0fnu)) for name in ('w1','w3','w2')}
            obj=SimpleNamespace(w1=lambda x:linear(x,weights['w1']),w3=lambda x:linear(x,weights['w3']),w2=lambda x:linear(x,weights['w2']),swiglu_limit=10.)
            for c in cases:
                rows,slots=torch.where(c['ids']==expert_id)
                if not rows.numel():continue
                expected=ns['forward'](obj,c['hidden'][rows],c['routing'][rows,slots,None])
                c['expected'][rows,slots]=expected
                c['experts'].append(dict(expert=expert_id,routes=rows.numel(),**compare(c['routed'][rows,slots],expected)))
            print(f'PASS expert={expert_id} reference_fp4=true',flush=True)
        for c in cases:
            expected=torch.zeros((80,5120),dtype=torch.float32)
            for slot in range(6):expected+=c['expected'][:,slot].float()
            expected+=c['shared'].float()
            results.append(dict(case=c['case'],rows=80,active_experts=len(c['experts']),ordered_transport_reduction_exact=True,routes=compare(c['routed'],c['expected']),ffn=compare(c['output'],expected.bfloat16()),experts=c['experts']))
            print(f"PASS case={c['case']} real_tp4_ffn=true {results[-1]['ffn']}",flush=True)
        stream.synchronize()
    a.output.write_text(json.dumps(dict(layer=a.layer,device=a.device,scope='One real backbone layer routed across four Spark TP ranks plus RTX shared expert; full-model execution remains open',
        reference_quantizer_compiler_overrides={'tir.disable_vectorize':True},weight_payloads_sha256=hashes,payloads_sha256=payloads,cases=results),indent=2)+'\n')


if __name__=='__main__':main()
